local rsvp = require("rsvp")
local create_user_command = vim.api.nvim_create_user_command

create_user_command("Rsvp", rsvp.rsvp, { desc = "RSVP", range = "%" })
create_user_command("RsvpPlay", rsvp.play, { desc = "RSVP Play" })
create_user_command("RsvpPause", rsvp.pause, { desc = "RSVP Pause" })
create_user_command("RsvpReset", rsvp.reset, { desc = "RSVP Reset" })
create_user_command("RsvpDecreaseWpm", function()
  rsvp.adjust_wpm(-25)
end, { desc = "RSVP Increase WPM" })
create_user_command("RsvpIncreaseWpm", function()
  rsvp.adjust_wpm(25)
end, { desc = "RSVP Increase WPM" })
create_user_command("RsvpPreviousStep", function()
  rsvp.set_step(-1)
end, { desc = "RSVP Previous Step" })
create_user_command("RsvpNextStep", function()
  rsvp.set_step(1)
end, { desc = "RSVP Next Step" })
